services:
  app:
    image: ghcr.io/cloudcranesss/tgstate-uploader:latest
    container_name: tgstate-uploader
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./data:/data
    environment:
      # 请根据实际情况修改 API 地址
      - BASE_URL=http://localhost:8088
      # 如果需要密码，请在此处设置
      - TGSTATE_PASS=
